package org.myproject.domain

import io.quarkus.mongodb.panache.common.MongoEntity
import org.bson.types.ObjectId
import java.time.LocalDateTime

@MongoEntity(collection = "flights")
data class Flight(
    var flightNumber: String,
    var origin: Location,
    var destination: Location,
    var departureTime: LocalDateTime,
    var arrivalTime: LocalDateTime,
    var aircraftId: String,
    var availableSeats: Int,
    var pricePerSeat: Map<String, Double> // economy, business, first
) {
    var id: ObjectId? = null // Automatically generated by MongoDB

    data class Location(
        var code: String,
        var name: String,
        var city: String,
        var country: String
    )
}
