package org.myproject.domain

import io.quarkus.mongodb.panache.common.MongoEntity
import org.bson.types.ObjectId

@MongoEntity(collection = "passengers")
data class Passenger(
    var bookingId: String,
    var name: String,
    var age: Int,
    var gender: String,
    var passportNumber: String,
    var nationality: String,
    var frequentFlyerNumber: String? = null,
    var specialRequests: List<String>? = null
) {
    var id: ObjectId? = null // Automatically generated by MongoDB
}
