package org.myproject.domain

import io.quarkus.mongodb.panache.common.MongoEntity
import org.bson.types.ObjectId
import java.time.LocalDateTime

@MongoEntity(collection = "payments")
data class Payment(
    var bookingId: String,
    var paymentDate: LocalDateTime,
    var amount: Double,
    var paymentMethod: String, // credit_card, paypal, bank_transfer
    var cardDetails: CardDetails?,
    var status: String // completed, pending, failed
) {
    var id: ObjectId? = null // Automatically generated by MongoDB

    data class CardDetails(
        var cardNumber: String,
        var cardHolder: String,
        var expirationDate: String
    )
}