package org.myproject.domain

import io.quarkus.mongodb.panache.common.MongoEntity
import org.bson.types.ObjectId

@MongoEntity(collection = "seats")
data class Seat(
    var flightId: String,
    var seatNumber: String,
    var seatClass: String, // economy, business, first
    var status: String, // reserved, available, blocked
    var userId: String? = null // null if not booked
) {
    var id: ObjectId? = null // Automatically generated by MongoDB
}
